bioreactor_prefix: 'B'

prior_initial_species:
    s: [9.77226E+10, 9.77226E+10]       # Extracellular nutrients

prior_paramters:
    d_s: [0.0, 0.0]     # Rate of efflux
    k_in: [0.0, 0.0]    # Rate of influx